export const props = {
  buildId: 'development',
  gssp: true,
  isFallback: false,
  page: '/packages/[package]/versions/[version]',
  props: {
    __N_SSP: true,
    pageProps: {
      metadata: {
        canonicalLink: '/packages/seewave/versions/2.2.3',
        description:
          'seewave provides functions for analysing, manipulating, displaying, editing and synthesizing time waves (particularly sound).  This package processes time analysis (oscillograms and envelopes), spectral content, resonance quality factor, entropy, cross correlation and autocorrelation, zero-crossing, dominant frequency, analytic signal, frequency coherence, 2D and 3D spectrograms and many other analyses.',
        license: 'GPL (\u003e= 2)',
        maintainer: {
          api_uri: '/api/collaborators/534675',
          created_at: '2016-08-05T10:36:35.000Z',
          email: 'sueur@mnhn.fr',
          gravatar_url:
            'https://www.gravatar.com/avatar/d08d5fb360b79c934c75cf454845b2d1',
          id: 534675,
          name: 'Jerome Sueur',
          updated_at: '2016-08-05T10:36:35.000Z',
          uri: '/collaborators/name/Jerome%20Sueur',
        },
        package: { type_id: 1 },
        package_name: 'seewave',
        pageTitle: 'seewave package',
        readmemd: null,
        release_date: '2014-01-27T11:11:24.000Z',
        title: 'Sound analysis and synthesis',
        topics: [
          { id: 116879, name: 'ACI', title: 'Acoustic Complexity Index' },
          {
            id: 116880,
            name: 'ccoh',
            title: 'Continuous coherence function between two time waves',
          },
          { id: 116881, name: 'cutspec', title: 'Cut a frequency spectrum' },
          {
            id: 116882,
            name: 'dBscale',
            title: 'dB colour scale for a spectrogram display',
          },
          {
            id: 116883,
            name: 'diffspec',
            title: 'Difference between two frequency spectra',
          },
          { id: 116884, name: 'discrets', title: 'Time series discretisation' },
          {
            id: 116885,
            name: 'diffwave',
            title: 'Difference between two time waves',
          },
          {
            id: 116886,
            name: 'env',
            title: 'Amplitude envelope of a time wave',
          },
          { id: 116887, name: 'ftwindow', title: 'Fourier transform windows' },
          { id: 116891, name: 'kl.dist', title: 'Kullback-Leibler distance' },
          {
            id: 116892,
            name: 'Q',
            title: 'Resonance quality factor of a frequency spectrum',
          },
          {
            id: 116893,
            name: 'dfreq',
            title: 'Dominant frequency of a time wave',
          },
          { id: 116894, name: 'ks.dist', title: 'Kolmogorov-Smirnov distance' },
          {
            id: 116895,
            name: 'drawenv',
            title: 'Draw the amplitude envelope of a time wave',
          },
          {
            id: 116896,
            name: 'ggspectro',
            title: '2D-spectrogram of a time wave using ggplot2',
          },
          { id: 116897, name: 'fund', title: 'Fundamental frequency track' },
          { id: 116898, name: 'pulse', title: 'Generate rectangle pulse' },
          {
            id: 116899,
            name: 'zapsilw',
            title: 'Zap silence periods of a time wave',
          },
          { id: 116900, name: 'playlist', title: 'Play a list of sound files' },
          {
            id: 116901,
            name: 'sh',
            title: 'Shannon and Renyi spectral entropy',
          },
          { id: 116902, name: 'itakura.dist', title: 'Itakuro-Saito distance' },
          { id: 116905, name: 'mel', title: 'Hertz / Mel conversion' },
          { id: 116906, name: 'noisew', title: 'Generate noise' },
          {
            id: 116908,
            name: 'oscilloST',
            title: 'Show a stereo time wave as oscillograms',
          },
          {
            id: 116909,
            name: 'simspec',
            title: 'Similarity between two frequency spectra',
          },
          { id: 116914, name: 'fpeaks', title: 'Frequency peak detection' },
          {
            id: 116915,
            name: 'attenuation',
            title: 'Generate sound intensity attenuation data',
          },
          {
            id: 116916,
            name: 'phaseplot',
            title: 'Phase-phase 2D or 3D plot of a time wave',
          },
          {
            id: 116917,
            name: 'deletew',
            title: 'Delete a section of a time wave',
          },
          { id: 116918, name: 'wf', title: 'Waterfall display' },
          {
            id: 116920,
            name: 'spectro3D',
            title: '3D-spectrogram of a time wave',
          },
          {
            id: 116921,
            name: 'seewave-internal',
            title: 'Internal Seewave Functions',
          },
          { id: 116922, name: 'resamp', title: 'Resample a time wave' },
          { id: 116923, name: 'wasp', title: 'WAve length and SPeed of sound' },
          { id: 116924, name: 'wav2flac', title: 'wav-flac file conversion' },
          {
            id: 116926,
            name: 'oscillo',
            title: 'Show a time wave as an oscillogram',
          },
          {
            id: 116927,
            name: 'tico',
            title: 'Song of the bird Zonotrichia capensis',
          },
          { id: 116929, name: 'specprop', title: 'Spectral properties' },
          {
            id: 117559,
            name: 'TKEO',
            title: 'Teager-Kaiser energy tracking operator',
          },
          {
            id: 117561,
            name: 'convSPL',
            title: 'Convert sound pressure level in other units',
          },
          {
            id: 117572,
            name: 'autoc',
            title: 'Short-term autocorrelation of a time wave',
          },
          { id: 117573, name: 'fma', title: 'Frequency modulation analysis' },
          {
            id: 117574,
            name: 'diffenv',
            title: 'Difference between two amplitude envelopes',
          },
          {
            id: 117575,
            name: 'coh',
            title: 'Coherence between two time waves',
          },
          { id: 117599, name: 'ifreq', title: 'Instantaneous frequency' },
          { id: 117600, name: 'listen', title: 'Play a sound wave' },
          {
            id: 117601,
            name: 'micsens',
            title: 'Microphone sensitivity and conversion',
          },
          { id: 117602, name: 'lfs', title: 'Linear Frequency Shift' },
          {
            id: 117643,
            name: 'notefreq',
            title: 'Frequency of a muscical note',
          },
          { id: 117644, name: 'fdoppler', title: 'Doppler effect' },
          { id: 117649, name: 'rmnoise', title: 'Remove noise' },
          {
            id: 117650,
            name: 'rmoffset',
            title: 'Remove the offset of a time wave',
          },
          { id: 117651, name: 'savewav', title: 'Save a .wav file' },
          { id: 117654, name: 'sfm', title: 'Spectral Flatness Measure' },
          { id: 117670, name: 'sox', title: 'Calls SoX' },
          {
            id: 117672,
            name: 'symba',
            title: 'Symbol analysis of a numeric (time) series',
          },
          {
            id: 117673,
            name: 'acoustat',
            title: 'Statistics on time and frequency STFT contours',
          },
          { id: 117679, name: 'rms', title: 'Root Mean Square' },
          {
            id: 117704,
            name: 'fadew',
            title: 'Fade in and fade out of a time wave',
          },
          {
            id: 117707,
            name: 'mutew',
            title: 'Replace time wave data by 0 values',
          },
          {
            id: 117723,
            name: 'rmam',
            title: 'Remove the amplitude modulations of a time wave',
          },
          { id: 117724, name: 'csh', title: 'Continuous spectral entropy' },
          {
            id: 117728,
            name: 'spectro',
            title: '2D-spectrogram of a time wave',
          },
          { id: 117740, name: 'octaves', title: 'Octave values' },
          { id: 117741, name: 'fir', title: 'Finite Impulse Response filter' },
          {
            id: 117742,
            name: 'seewave',
            title: 'Sound analysis and synthesis',
          },
          {
            id: 121152,
            name: 'SAX',
            title: 'Symbolic Aggregate approXimation',
          },
          {
            id: 121153,
            name: 'corenv',
            title: 'Cross-correlation between two time wave envelopes',
          },
          { id: 121154, name: 'fbands', title: 'Frequency bands plot' },
          { id: 121155, name: 'export', title: 'Export sound data' },
          {
            id: 121156,
            name: 'addsilw',
            title: 'Add or insert a silence section',
          },
          {
            id: 121157,
            name: 'field',
            title: 'Near field and far field limits',
          },
          {
            id: 121158,
            name: 'meanspec',
            title: 'Mean frequency spectrum of a time wave',
          },
          {
            id: 121160,
            name: 'pastew',
            title: 'Paste a time wave to another one',
          },
          { id: 121161, name: 'orni', title: 'Song of the cicada Cicada orni' },
          {
            id: 121170,
            name: 'pellucens',
            title: 'Calling song of the tree cricket Oecanthus pellucens',
          },
          { id: 121172, name: 'repw', title: 'Repeat a time wave' },
          {
            id: 121173,
            name: 'seedata',
            title: 'A quick look at quantitative data',
          },
          {
            id: 121174,
            name: 'ama',
            title: 'Amplitude modulation analysis of a time wave',
          },
          {
            id: 121175,
            name: 'smoothw',
            title: 'A function to tentavily smooth a time wave',
          },
          { id: 121179, name: 'sheep', title: 'Sheep bleat' },
          {
            id: 121180,
            name: 'hilbert',
            title: 'Hilbert transform and analytic signal',
          },
          {
            id: 121181,
            name: 'synth2',
            title: 'Synthesis of time wave (tonal model)',
          },
          { id: 121186, name: 'dBweight', title: 'dB weightings' },
          { id: 121357, name: 'H', title: 'Total entropy' },
          { id: 121358, name: 'afilter', title: 'Amplitude filter' },
          {
            id: 121359,
            name: 'cepstro',
            title: '2D-cepstrogram of a time wave',
          },
          {
            id: 121361,
            name: 'corspec',
            title: 'Cross-correlation between two frequency spectra',
          },
          { id: 121362, name: 'cutw', title: 'Cut a section of a time wave' },
          {
            id: 121363,
            name: 'covspectro',
            title: 'Covariance between two spectrograms',
          },
          {
            id: 121365,
            name: 'NDSI',
            title: 'Normalized Difference Soundscape Index',
          },
          { id: 121366, name: 'dynspec', title: 'Dynamic sliding spectrum' },
          { id: 121367, name: 'ceps', title: 'Cepstrum or real cepstrum' },
          { id: 121373, name: 'ffilter', title: 'Frequency filter' },
          { id: 121378, name: 'logspec.dist', title: 'Log-spectral distance' },
          { id: 121379, name: 'dynoscillo', title: 'Dynamic oscillogram' },
          {
            id: 121386,
            name: 'localpeaks',
            title: 'Local maximum frequency peak detection',
          },
          {
            id: 121388,
            name: 'peewit',
            title: 'Song of the bird Vanellus vanellus',
          },
          { id: 121389, name: 'revw', title: 'Time reverse of a time wave' },
          {
            id: 121391,
            name: 'roughness',
            title: 'Roughness or total curvature',
          },
          { id: 121392, name: 'rugo', title: 'Rugosity of a time wave' },
          {
            id: 121394,
            name: 'spec',
            title: 'Frequency spectrum of a time wave',
          },
          { id: 121395, name: 'zcr', title: 'Zero-crossing rate' },
          {
            id: 121396,
            name: 'sddB',
            title: 'Standard deviation of dB values',
          },
          { id: 121401, name: 'moredB', title: 'Addition of dB values' },
          { id: 121406, name: 'meandB', title: 'Mean of dB values' },
          { id: 121410, name: 'th', title: 'Temporal entropy' },
          {
            id: 121411,
            name: 'setenv',
            title: 'Set the amplitude envelope of a time wave to another one',
          },
          {
            id: 121414,
            name: 'stft.ext',
            title:
              'Short-term Fourier transform using fftw and libsndfile C libraries',
          },
          {
            id: 121415,
            name: 'timer',
            title: 'Time measurements of a time wave',
          },
          {
            id: 121416,
            name: 'soundscapespec',
            title: 'Soundscape frequency spectrum of a time wave',
          },
          {
            id: 121419,
            name: 'synth',
            title: 'Synthesis of time wave (additive model)',
          },
          {
            id: 121420,
            name: 'crest',
            title: 'Crest factor and visualization',
          },
          { id: 121421, name: 'echo', title: 'Echo generator' },
          {
            id: 121428,
            name: 'zc',
            title: 'Instantaneous frequency of a time wave by zero-crossing',
          },
        ],
        type_id: 1,
        uri: '/packages/seewave/versions/1.7.3',
        version: '1.7.3',
      },
      monthlyDownloads: [
        { downloads: 3038, month: 'September 2023' },
        { downloads: 4702, month: 'October 2023' },
        { downloads: 3748, month: 'November 2023' },
        { downloads: 2714, month: 'December 2023' },
        { downloads: 3123, month: 'January 2024' },
        { downloads: 2900, month: 'February 2024' },
        { downloads: 3096, month: 'March 2024' },
        { downloads: 3147, month: 'April 2024' },
        { downloads: 3774, month: 'May 2024' },
        { downloads: 2919, month: 'June 2024' },
        { downloads: 3054, month: 'July 2024' },
        { downloads: 2646, month: 'August 2024' },
      ],
      repository: null,
      urls: { githubUrl: null, homeUrl: null },
      versionsArray: [
        '2.2.3',
        '2.2.2',
        '2.2.1',
        '2.2.0',
        '2.1.8',
        '2.1.6',
        '2.1.5',
        '2.1.4',
        '2.1.3',
        '2.1.0',
        '2.0.5',
        '2.0.4',
        '2.0.2',
        '2.0.1',
        '1.7.6',
        '1.7.3',
        '1.7.2',
        '1.7.0',
        '1.6.7',
        '1.6.5',
        '1.6.4',
        '1.6.3',
        '1.6.2',
        '1.6.1',
        '1.6.0',
        '1.5.9',
        '1.5.8',
        '1.5.7',
        '1.5.6',
        '1.5.5',
        '1.5.4',
        '1.5.2',
        '1.5.1',
        '1.5.0',
        '1.4.9',
        '1.4.8',
        '1.4.7',
        '1.4.6',
        '1.4.5',
        '1.4.4',
        '1.4.3',
        '1.4.2',
        '1.4.1',
        '1.3',
        '1.2',
        '1.1',
        '1.0',
      ],
    },
  },
  query: { package: 'seewave', version: '1.7.3' },
};
